#!/usr/bin/env python3
import pyautogui
import time
from datetime import datetime
#pyautogui.FAILSAFE=False
x=59.97
debugger=True
def TRAMPSTAMP():
	now = datetime.now()
	date_time = now.strftime("%Y%m%d@%H:%M:%S")
	return date_time
try:
	while True:
		if (debugger == True):
			print("Wiggling: ", TRAMPSTAMP())
		pyautogui.move(0, 1, .01)
		pyautogui.move(-1, -1, .01)
		pyautogui.move(1, 0, .01)
		time.sleep(x)
except KeyboardInterrupt:
    pass
except Exception as e:
    print(f"Error wiggling mouse: {e}")
    exit(1)
